print("Write a program to print numbers from 1 to 30 using for loop.\n")

for i in range(1,31):
    print(i)

print("Write a program to print even numbers from 1 to 50 using while loop.\n")

num = 1
while num <= 50:
    if num % 2 == 0:
        print(num)
    num += 1

print("Write a program to print multiplication table of a given number.\n")

num = int(input("Enter Table Number: "))

for i in range(1,11):
    print(f"{num} x {i} = ",num*i)

print("Write a program to print odd numbers from 1 to 50 using while loop.\n")

num = 1
while num <= 50:
    if num % 2 != 0:
        print(num)
    num += 1

print("Write a program to calculate the sum of all numbers from 1 to 50 using for loop.\n")

sum=0
for i in range(1,51):
    sum=sum+i
    print(sum)
print("\nThe total Sum is : ",sum)

print("\nWrite a program to print each character of a string.\n")

text = input("Enter String: ")
for char in text:
    print(char)

print("\nWrite a program to compute the factorial of a number using while loop.\n")

num = int(input("Enter a number: "))

factorial = 1
i = 1

while i <= num:
    factorial *= i
    i += 1

print("Factorial of", num, "is", factorial)

print("\nWrite a program to print numbers from 10 down to 1. [Hint: first check the sequence generated by range function on IDLE using this command i.e. list(range(10, 0, -1))]\n")

print(list(range(10,1,-1)))
        # OR
for i in range(10,0,-1):
    print(i)

print("\nWrite a program that continues to ask user to input password until the correct password is entered.\n")

while True:
    pasw = int(input("Enter Your Password: "))
    if pasw == 1234:
        print("Correct Password")
        break


print("\nWrite a program to print the square of each number from 1 to 10 using for loop.\n")
    
for i in range(1,11):
    print(i**2)

print("\nWrite a program to calculate the sum of even and odd numbers and print them. (numbers from 1 to 50)\n")

even = 0
odd = 0

for number in range(1,51):
    if number%2 == 0:
        number+=even
    else:
        number+=odd
print("Even is: ",even)
print("Odd is: ",odd)


print("\nWrite a program to print the first 10 Fibonacci numbers using for loop. Hint: First 10 Fibanacci numbers are  0,1,1,2,3,5,8,13,21,34\n")

a = 0
b = 1

for i in range(10):
    print(a)
    a,b = b,a + b

    





